spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ogani
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true